name: WCAG Accessibility Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'  # Segunda-feira às 8h

jobs:
  wcag-accessibility-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Robot Framework
        run: |
          python -m pip install --upgrade pip
          pip install robotframework==5.0.1
          echo "Robot Framework instalado com sucesso."
        
      - name: Create Report Directories
        run: |
          mkdir -p reports/accessibility/temp
          chmod -R 777 reports/accessibility
          echo "Diretórios de relatórios criados com sucesso."
      
      - name: Run WCAG Accessibility Tests
        run: |
          echo "Executando testes de conformidade WCAG..."
          robot --outputdir results tests/accessibility_tests/wcag_test.robot
          echo "Testes WCAG concluídos."
        
      - name: Generate Summary
        run: |
          echo "## Relatório de Conformidade WCAG" > wcag_summary.md
          echo "" >> wcag_summary.md
          
          # Adicionar detalhes de cada site testado
          for report in reports/accessibility/wcag_summary_*.md; do
            if [ -f "$report" ]; then
              url=$(grep -m 1 "URL:" "$report" | cut -d' ' -f2-)
              echo "### $url" >> wcag_summary.md
              echo "" >> wcag_summary.md
              
              # Verificar se há violações
              if grep -q "Nenhuma violação WCAG encontrada" "$report"; then
                echo "✅ **Nenhuma violação WCAG encontrada!**" >> wcag_summary.md
              else
                violations=$(grep -m 1 "violações WCAG encontradas" "$report" | cut -d' ' -f1 | tr -d '❌')
                echo "❌ **$violations violações WCAG encontradas**" >> wcag_summary.md
                echo "" >> wcag_summary.md
                echo "Principais problemas:" >> wcag_summary.md
                
                # Extrair tabela de violações (até 5 primeiras)
                awk '/\| # \| Regra/{flag=1; count=0} flag && count<6{print; count++}' "$report" >> wcag_summary.md
              fi
              echo "" >> wcag_summary.md
              echo "---" >> wcag_summary.md
              echo "" >> wcag_summary.md
            fi
          done
          
          echo "Para detalhes completos, consulte os relatórios nos artefatos." >> wcag_summary.md

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: wcag-accessibility-results
          path: |
            results/
            reports/accessibility/
            wcag_summary.md