name: CI

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório na variável $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instala as dependências do Robot Framework
      - name: Install Robot Framework
        run: |
          python -m pip install --upgrade pip
          pip install robotframework

      # Executa os testes do Robot Framework
      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      # Faz o upload dos relatórios gerados como artefatos
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/