# Este é um fluxo de trabalho básico para ajudar você a começar com Actions

name: CI

# Controle de quando o fluxo de trabalho será executado
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Um fluxo de trabalho é composto por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório na variável $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Executa os testes e gera um relatório
      - name: Run Tests and Generate Report
        run: |
          npm install  # Certifique-se de instalar as dependências antes de rodar os testes
          npm test -- --reporter=spec > test-report.txt
        continue-on-error: false  # Garante que o fluxo falhe se os testes falharem

      # Faz o upload do relatório gerado como artefato
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt
