name: CI Details

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Log Checkout Completion
        run: echo "Código fonte verificado com sucesso."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Dependencies
        run: |
          echo "Instalando dependências do projeto..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependências instaladas com sucesso."

      - name: Create Directories for K6
        run: |
          mkdir -p tests/performance_tests/k6_scripts
          mkdir -p reports/performance
          echo "Diretórios para testes K6 criados com sucesso."

      - name: Pull K6 Docker Image
        run: |
          echo "Baixando a imagem Docker do K6..."
          docker pull grafana/k6:latest
          echo "Imagem Docker do K6 baixada com sucesso."

      - name: Run Robot Framework Tests
        run: |
          echo "Executando os testes do Robot Framework..."
          robot --outputdir results tests/

      - name: Extract Test Results
        run: |
          echo "Testes que passaram:"
          grep 'status="PASS"' results/output.xml | awk -F\" '{print $6}' || echo "Nenhum teste passou"
          echo "Testes que falharam:"
          grep 'status="FAIL"' results/output.xml | awk -F\" '{print $6}' || echo "Nenhum teste falhou"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            results/
            reports/performance/
      - name: Log Upload Completion
        run: echo "Relatórios de testes enviados como artefatos com sucesso. Veja os resultados completos em 'results/report.html'."