name: CI Performance Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Log Checkout Completion
        run: echo "Código fonte verificado com sucesso."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Dependencies
        run: |
          echo "Instalando dependências do projeto..."
          python -m pip install --upgrade pip
          pip install robotframework==5.0.1
          pip install robotframework-seleniumlibrary==6.0.0
          pip install requests==2.32.0 pyyaml==6.0.2
          echo "Dependências instaladas com sucesso."

      - name: Create Directories
        run: |
          mkdir -p reports/performance
          echo "Diretórios para testes criados com sucesso."
          
      - name: Verify Docker
        run: |
          docker --version
          docker info

      - name: Pull K6 Docker Image
        run: docker pull grafana/k6:latest

      - name: Run Performance Tests
        run: |
          echo "Executando os testes de performance..."
          robot --outputdir results/performance tests/performance_tests/performance_k6_test.robot

      - name: Run Other Tests
        run: |
          echo "Executando os demais testes (quando existirem)..."
          robot --outputdir results --exclude performance tests/ || true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            results/
            reports/
      - name: Log Upload Completion
        run: echo "Relatórios de testes enviados como artefatos com sucesso."